### ISSUE TITLE
Literally proves nothing?

### ISSUE THREAD

**Issue by x4e** [RIPBackdoored/cookiedragon234-is-cancelled#1]

**Comment by Crystallinqq** [comment]
wheres proof its backdoored tho? Still havent posted any proof, sweetie

**Comment by cookiedragon234** [comment]
@Crystallinqq why should I give a shit, if you want to trust child go ahead, but just remember that nothing is ever for free.

**Comment by RIPBackdoored** [comment]
hey cookie you went to far. get ready to experience some turbulence.

**Comment by ghost** [comment]
@RIPBackdoored Thanks for all the cracks 👍

**Comment by RIPBackdoored** [comment]
> @Crystallinqq why should I give a shit, if you want to trust child go ahead, but just remember that nothing is ever for free.

read the readme.md again, I've updated with the definitive proof that you created the infected crack

**Comment by cookiedragon234** [comment]
@RIPBackdoored In response to your "definitive proof"

1. Plenty of obfuscators have invokedynamic method indirection, including free ones like Jobf, an obfuscator that I worked on.

2. paramorphism 2.0 is public, everyone who owns paramorphism can download the beta

Nice damage control but you arent fooling anyone

**Comment by Crystallinqq** [comment]
@cookiedragon234 then show proof of CHILD's original crack being backdoored. we have proof of u having ur fake crack sending coords to a webhook. nice damage control but you arent fooling anyone.

**Comment by cookiedragon234** [comment]
@Crystallinqq tfw, you have 0 proof I spread any crack whatsoever

**Comment by Crystallinqq** [comment]
@cookiedragon234 dodging the question? tiger doesnt seem to agree that u didnt spread any crack. Also in your reddit post, you said you found his "endpoint" in the crack and "downloaded the logs" please show links or some kind of proof you can use to defend yourself/prove yourself correct. All the evidence seems to be pointing to you :(

**Comment by cookiedragon234** [comment]
Literally what evidence? There is none. And Im not going to give anyone coords or leak the endpoint or anything as there was a controversial reaction to the first couple of coords.

**Comment by Crystallinqq** [comment]
@cookiedragon234 u dont have any evidence? read the dm ur dev sent me when we talked on the github page. tiger sure seems to know u backdoored and made the crack bro. idk why ur trying to cover it up, may aswell just apologize normally and maybe people will respect you more than trying to say you didnt do anything and ur so good

**Comment by cookiedragon234** [comment]
Oh my bad because someone has a screenshot of a discord conversation I should trust him? Not like screenshots can be faked right? My bad

> Implying im the one trying to cover up

Stop trying to blame something on me with absolutely 0 evidence.

**Comment by Crystallinqq** [comment]
@cookiedragon234 i have screenshots from before of the full window and after showing that he deleted the message. unblock me and ill send u it <3

**Comment by Katatje** [comment]
lol

**Comment by cookiedragon234** [comment]
@Crystallinqq imagine actually thinking that anyone trusts discord screenshots lmao

**Comment by cookiedragon234** [comment]
After discussing this with CHILD in private I've explained to him exactly what happened and I will also put this here.

The crack that has been spread by the account "CH1LD" on gitlab.com was indeed created by me. I created a seperate branch of the main source code that is distributed to customers, added code that would routinely send info about the current user such as current server, coordinates etc to a discord webhook that I had access to. This was *completely* seperate from the main branch of the source code and there is absolutely no sort of code within the binaries that are distributed to customers. This seperate branch was not meant to be spread, but given to a specific person who had been repeatedly causing trouble. It appears they created a gitlab account with the alias "CH1LD" and spread the crack.


I feel that I should also add to this comment a warning about trusting files off the internet. Downloading any jar, especially one uploaded to a public website for free, should always be done with caution. There are plenty of tools out there to try and help you identify malicious software, and if you yourself cannot use them, ask someone you trust to check for you.

**Comment by Crystallinqq** [comment]
homie deleted all his comments

**Comment by Crystallinqq** [comment]
@cookiedragon234 why did you try to say it was CHILD though? makes no sense bro

**Comment by 5HT2** [comment]
Because it looked like child dumbass

**Comment by char** [comment]
hi um Paramorphism 2.0 has been generally available to all customers for several days, it's just hidden away while I prepare the new website's backend

**Comment by Crystallinqq** [comment]
ur late to the convo anthony

**Comment by 5HT2** [comment]
^
drama over

cookiedragon dead

**Comment by cookiedragon234** [comment]
I died???!?!?

**Comment by 5HT2** [comment]
yes 😳😳
